<script setup lang="ts">
import { ref, watch, onUnmounted } from 'vue'
import { usePlannerStore } from '../stores/plannerStore'

withDefaults(
  defineProps<{
    kind: 'building' | 'item'
    id: string
    name: string
    size?: number
  }>(),
  { size: 24 },
)

const store = usePlannerStore()
const failed = ref(false)

function onError() {
  failed.value = true
}

// Fallback: first 1-2 letters of name, uppercase
function fallbackLabel(name: string): string {
  const words = name.trim().split(/\s+/)
  if (words.length >= 2) {
    return (words[0][0] + words[1][0]).toUpperCase()
  }
  return name.slice(0, 2).toUpperCase()
}

// ── Hover zoom ──────────────────────────────────────────────────────────────
const ZOOM_SIZE = 160 // px – rendered preview size
const DELAY_MS = 500 // hover dwell / press-and-hold before popup shows

// Module-level timestamp to suppress synthetic mouse events generated by touch
let lastTouchTimestamp = 0

const zoom = ref(false)
const zoomX = ref(0)
const zoomY = ref(0)
let hoverTimer: ReturnType<typeof setTimeout> | null = null
let touchStartX = 0
let touchStartY = 0

function scheduleZoom(clientX: number, clientY: number) {
  clearZoomTimer()
  // Capture coordinates now — don't close over the event object (stale after dispatch)
  hoverTimer = setTimeout(() => {
    positionZoom(clientX, clientY)
    zoom.value = true
  }, DELAY_MS)
}

function positionZoom(cx: number, cy: number) {
  const padding = 8
  const half = ZOOM_SIZE / 2
  let x = cx - half
  let y = cy - ZOOM_SIZE - padding - 16
  x = Math.max(padding, Math.min(x, window.innerWidth - ZOOM_SIZE - padding))
  if (y < padding) y = cy + 20
  zoomX.value = x
  zoomY.value = y
}

function onMouseEnter(e: MouseEvent) {
  if (Date.now() - lastTouchTimestamp < 1500) return
  if ('pointerType' in e && (e as PointerEvent).pointerType === 'touch') return
  scheduleZoom(e.clientX, e.clientY)
}

function onMouseMove(e: MouseEvent) {
  if (Date.now() - lastTouchTimestamp < 1500) return
  if (!zoom.value) return
  positionZoom(e.clientX, e.clientY)
}

function onMouseLeave() {
  clearZoomTimer()
  zoom.value = false
}

// Touch / press-and-hold
function onTouchStart(e: TouchEvent) {
  lastTouchTimestamp = Date.now()
  const t = e.touches[0]
  if (!t) return
  touchStartX = t.clientX
  touchStartY = t.clientY
  scheduleZoom(t.clientX, t.clientY)
}

function onTouchMove(e: TouchEvent) {
  const t = e.touches[0]
  if (!t) return
  const dist = Math.hypot(t.clientX - touchStartX, t.clientY - touchStartY)
  if (dist > 8) {
    dismissZoom()
  }
}

function onTouchEnd() {
  dismissZoom()
}

function clearZoomTimer() {
  if (hoverTimer !== null) {
    clearTimeout(hoverTimer)
    hoverTimer = null
  }
}

function dismissZoom() {
  clearZoomTimer()
  zoom.value = false
}

watch(zoom, (isZoomed) => {
  if (isZoomed) {
    window.addEventListener('scroll', dismissZoom, { passive: true })
  } else {
    window.removeEventListener('scroll', dismissZoom)
  }
})

onUnmounted(() => {
  clearZoomTimer()
  window.removeEventListener('scroll', dismissZoom)
})
</script>

<template>
  <!-- When showIcons is off: render nothing -->
  <template v-if="!store.showIcons" />

  <!-- When showIcons is on but image failed: render letter glyph -->
  <span
    v-else-if="failed"
    class="inline-flex items-center justify-center rounded bg-[var(--panel-2)] text-[var(--muted)] font-bold select-none shrink-0"
    :style="{ width: `${size}px`, height: `${size}px`, fontSize: `${Math.max(8, size * 0.45)}px` }"
    :title="name"
  >
    {{ fallbackLabel(name) }}
  </span>

  <!-- Normal image with hover-zoom -->
  <span
    v-else
    class="inline-flex shrink-0"
    :style="{ width: `${size}px`, height: `${size}px` }"
    @mouseenter="onMouseEnter"
    @mousemove="onMouseMove"
    @mouseleave="onMouseLeave"
    @touchstart.passive="onTouchStart"
    @touchmove.passive="onTouchMove"
    @touchend.passive="onTouchEnd"
    @touchcancel.passive="onTouchEnd"
  >
    <img
      :src="`/icons/${kind}s/${id}.webp`"
      :alt="name"
      :width="size"
      :height="size"
      loading="lazy"
      class="rounded object-contain w-full h-full"
      @error="onError"
    />

    <!-- Teleport zoom preview to body so it's never clipped -->
    <Teleport to="body">
      <Transition
        enter-active-class="transition-all duration-200 ease-out"
        enter-from-class="opacity-0 scale-75"
        enter-to-class="opacity-100 scale-100"
        leave-active-class="transition-all duration-150 ease-in"
        leave-from-class="opacity-100 scale-100"
        leave-to-class="opacity-0 scale-75"
      >
        <div
          v-if="zoom"
          class="fixed pointer-events-none select-none"
          :style="{
            left: `${zoomX}px`,
            top: `${zoomY}px`,
            width: `${ZOOM_SIZE}px`,
            height: `${ZOOM_SIZE}px`,
            zIndex: 2147483647,
          }"
        >
          <!-- Backdrop card -->
          <div
            class="w-full h-full rounded-xl flex items-center justify-center p-2"
            style="
              background: var(--panel-2);
              border: 1px solid var(--border);
              box-shadow: 0 8px 32px rgba(0, 0, 0, 0.6);
            "
          >
            <img
              :src="`/icons/${kind}s/${id}.webp`"
              :alt="name"
              class="object-contain w-full h-full rounded-lg"
            />
          </div>
          <!-- Name label below -->
          <div
            class="absolute left-1/2 -translate-x-1/2 mt-1.5 whitespace-nowrap text-xs font-semibold text-[var(--text-2)] px-2 py-0.5 rounded"
            style="background: var(--panel-2); border: 1px solid var(--border); top: 100%"
          >
            {{ name }}
          </div>
        </div>
      </Transition>
    </Teleport>
  </span>
</template>
