// AUTO-GENERATED by scripts/refresh-data.mjs — do not edit manually.
// Re-run `npm run refresh-data` to update when a new game version drops.

export interface VersionInfo {
  id: string
  label: string
}

export const VERSIONS: VersionInfo[] = [
  { id: 'playtest', label: 'Playtest' },
  { id: 'earlyaccess', label: 'Early Access' },
  { id: 'update1', label: 'Update 1' },
  { id: 'update1_PTB', label: 'Update 1 PTB' },
  { id: 'update2_QoL', label: 'Update 2 QoL' },
]

export const DEFAULT_VERSION = 'update2_QoL'
